apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: lm-webhook-mutating-webhook-configuration
webhooks:
- name: lm-webhook-svc.lm-webhook.svc.cluster.local
  objectSelector:
    matchExpressions:
      - key: type
        operator: In
        values:
        - application
    matchLabels:
        tier: backend
  namespaceSelector:
      matchExpressions:
      - key: environment
        operator: In
        values:
        - dev
