apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: test-mutatingWebhookConfiguration
webhooks:
- name: test-webhook
  objectSelector:
    matchLabels:
      lm-webhook: enabled
  namespaceSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - dev
