lmEnvVars:
  resource:
    - env: 
        name: SERVICE_ACCOUNT_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
      resAttrName: serviceaccount.name
      overrideDisabled: true
  operation:
    - env:
        name: COMPANY_NAME
        value: BBB Corporation
      overrideDisabled: true 
    - env:
        name: EXPORTER_ENDPOINT
        value: lmotel-svc.logicmonitor.svc.cluster.local:4317
      overrideDisabled: true 
    - env:
        name: OTEL_JAVAAGENT_ENABLED
        value: true
      overrideDisabled: true
    - env:
        name: DEPLOYMENT_ENV
        value: production
